version: '3.8'

services:
  keycloak:
    container_name: autolavaggio-keycloak
    image: quay.io/keycloak/keycloak:26.2
    ports:
      - "8081:8080"
    networks:
      - keycloak-network
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm.json:/opt/keycloak/data/import/Autolavaggio-Domicilio-realm.json
    command:
      - start-dev
      - --import-realm

networks:
  keycloak-network:
    driver: bridge